
spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/er-sols?useSSL=false
        url: jdbc:mysql://localhost:3309/trip-db?useSSL=false
        username: root
#        password: password
        password: accounts
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    main:
      banner-mode: "off"
    rabbitmq:
      host: ersols.online
urls:
  account-service: "localhost:8081"
  vehicle-service: "localhost:8080"
server:
  port: 8082
management:
    endpoints:
        web:
            exposure:
                include: prometheus, health, info
---
spring:
  profiles: docker-compose
  datasource:
      url: jdbc:mysql://trip-db:3306/trip-db?useSSL=false
      username: root
      password: accounts
  jpa:
    show-sql: false
urls:
  account-service: "account-service:8080"
  vehicle-service: "vehicle-service:8080"
server:
  port: 8080